$(document).ready(function(){
  //alert("hi")
  $("#frame").click(function(){
    	$("#print2").toggle();
    	});
      $("#print2").click(function(){
        	$("#print2").hide();
        	});
          $("#print2").click(function(){
            	$("#print1").show();
            	});
              $("#print1").click(function(){
                	$("#text5").show();
                	});
                  $("#print1").click(function(){
                    	$("#print1").css("cursor","auto");
                    	});
                  $("#wall").click(function(){
                    	$("#text1").show();
                    	});
                      $("#wall").click(function(){
                        	$("#wall").css("cursor","auto");
                        	});
                      $("#bed").click(function(){
                        	$("#text2").show();
                        	});
                          $("#bed").click(function(){
                            	$("#bed").css("cursor","auto");
                            	});
                          $("#pillow").click(function(){
                            	$("#text3").show();
                            	});
                              $("#pillow").click(function(){
                                	$("#pillow").css("cursor","auto");
                                	});
                              $("#cloth").click(function(){
                                	$("#text4").show();
                                	});
                                  $("#cloth").click(function(){
                                    	$("#cloth").css("cursor","auto");
                                    	});
                                      $("#song").click(function(){
                                        	$("#tape").show();
                                        	});
                                          $("#song").click(function(){
                                            	$("#print1").hide();
                                            	});
                                              $("#tape").click(function(){
                                                	$("#lyrics").show();
                                                	});


})
