$(document).ready(function(){
  //alert("hi")
  $("#girl4").click(function(){
    	$("#animation").show();
    	});
      $("#animation").click(function(){
        	$("#drawing1").show();
        	});
          $("#animation").click(function(){
              $("#drawing2").show();
              });
              $("#animation").click(function(){
                	$("#one1").hide();
                	});
                  $("#animation").click(function(){
                    	$("#two1").hide();
                    	});
                      $("#animation").click(function(){
                        	$("#three1").hide();
                        	});
                          $("#animation").click(function(){
                            	$("#four1").hide();
                            	});
                              $("#animation").click(function(){
                                	$("#four2").hide();
                                	});
                                  $("#animation").click(function(){
                                    	$("#animation").css("cursor","auto");
                                    	});
                                      $("#drawing1").click(function(){
                                        	$("#drawing11").toggle();
                                        	});
                                          $("#drawing2").click(function(){
                                            	$("#drawing22").toggle();
                                            	});
                                              $("#drawing2").click(function(){
                                                	$("#tape").show();
                                                	});
                                                  $("#drawing1").click(function(){
                                                    	$("#tape").show();
                                                    	});
                                                      $("#drawing2").click(function(){
                                                        	$("#hole2").show();
                                                        	});
                                                          $("#drawing1").click(function(){
                                                            	$("#hole2").show();
                                                            	});
                                                              $("#tape").click(function(){
                                                                	$("#lyrics1").show();
                                                                	});
                                                                  $("#tape").click(function(){
                                                                    	$("#lyrics2").show();
                                                                    	});
                                              $("#drawing11").click(function(){
                                                	$("#drawing11").hide();
                                                	});
                                                  $("#drawing22").click(function(){
                                                    	$("#drawing22").hide();
                                                    	});

                                                          $("#drawing1").click(function(){
                                                            	$("#drawing22").hide();
                                                            	});
                                                              $("#drawing2").click(function(){
                                                                	$("#drawing11").hide();
                                                                	});
                              $("#girl").click(function(){
                                	$("#girl2").show();
                                	});
                                  $("#girl2").click(function(){
                                    	$("#girl3").show();
                                    	});
                                      $("#girl3").click(function(){
                                        	$("#girl4").show();
                                        	});
                                          $("#girl").click(function(){
                                            	$("#girl").hide();
                                            	});
                                              $("#girl2").click(function(){
                                                	$("#girl2").hide();
                                                	});
                                                  $("#girl3").click(function(){
                                                    	$("#girl3").hide();
                                                    	});
                                                      $("#girl").click(function(){
                                                        	$("#one1").show();
                                                        	});
                                                          $("#girl").click(function(){
                                                            	$("#one2").show();
                                                            	});
                                                              $("#girl2").click(function(){
                                                                	$("#two1").show();
                                                                	});
                                                                  $("#girl2").click(function(){
                                                                    	$("#two2").show();
                                                                    	});
                                                                      $("#girl2").click(function(){
                                                                        	$("#one2").hide();
                                                                        	});
                                                                          $("#girl3").click(function(){
                                                                            	$("#three1").show();
                                                                            	});
                                                                              $("#girl3").click(function(){
                                                                                	$("#three2").show();
                                                                                	});
                                                                                  $("#girl3").click(function(){
                                                                                    	$("#two2").hide();
                                                                                    	});
                                                                                      $("#girl4").click(function(){
                                                                                          $("#four1").show();
                                                                                          });
                                                                                          $("#girl4").click(function(){
                                                                                              $("#four2").show();
                                                                                              });
                                                                                              $("#girl4").click(function(){
                                                                                                  $("#three2").hide();
                                                                                                  });
                                                                                                  $("#girl4").click(function(){
                                                                                                      $("#girl4").css("cursor","auto");
                                                                                                      });


})
