$(document).ready(function(){
  $("#sky").draggable();
  $("#ground").draggable();
  $("#grass").draggable();
  $("#men").draggable();
  $("#lake").draggable();
  $("#xiaoyu2").draggable();
  $("#backfire").draggable();
  $("#tape").click(function(){
      $("#lyrics1").show();
      });
      $("#tape").click(function(){
          $("#lyrics2").show();
          });
})
