$(document).ready(function(){
  //alert("hi")
  $("#png1").click(function(){
    	$("#text1").toggle();
    	});
      $("#png1").click(function(){
        	$("#text2").hide();
        	});
          $("#png1").click(function(){
            	$("#text3").hide();
            	});
              $("#png1").click(function(){
                	$("#text4").hide();
                	});
                  $("#png1").click(function(){
                    	$("#text5").hide();
                    	});
                      $("#png1").click(function(){
                        	$("#text6").hide();
                        	});
      $("#png2").click(function(){
          $("#text2").toggle();
          });
          $("#png2").click(function(){
            	$("#text1").hide();
            	});
              $("#png2").click(function(){
                	$("#text3").hide();
                	});
                  $("#png2").click(function(){
                    	$("#text4").hide();
                    	});
                      $("#png2").click(function(){
                        	$("#text5").hide();
                        	});
                          $("#png2").click(function(){
                            	$("#text6").hide();
                            	});
          $("#png3").click(function(){
              $("#text3").toggle();
              });
              $("#png3").click(function(){
                	$("#text2").hide();
                	});
                  $("#png3").click(function(){
                    	$("#text1").hide();
                    	});
                      $("#png3").click(function(){
                        	$("#text4").hide();
                        	});
                          $("#png3").click(function(){
                            	$("#text5").hide();
                            	});
                              $("#png3").click(function(){
                                	$("#text6").hide();
                                	});
              $("#png4").click(function(){
                  $("#text4").toggle();
                  });
                  $("#png4").click(function(){
                    	$("#text2").hide();
                    	});
                      $("#png4").click(function(){
                        	$("#text3").hide();
                        	});
                          $("#png4").click(function(){
                            	$("#text1").hide();
                            	});
                              $("#png4").click(function(){
                                	$("#text5").hide();
                                	});
                                  $("#png4").click(function(){
                                    	$("#text6").hide();
                                    	});
                  $("#png5").click(function(){
                      $("#text5").toggle();
                      });
                      $("#png5").click(function(){
                        	$("#text2").hide();
                        	});
                          $("#png5").click(function(){
                            	$("#text3").hide();
                            	});
                              $("#png5").click(function(){
                                	$("#text4").hide();
                                	});
                                  $("#png5").click(function(){
                                    	$("#text1").hide();
                                    	});
                                      $("#png5").click(function(){
                                        	$("#text6").hide();
                                        	});
                                      $("#me").click(function(){
                                          $("#text6").toggle();
                                          });
                                          $("#me").click(function(){
                                            	$("#text2").hide();
                                            	});
                                              $("#me").click(function(){
                                                	$("#text3").hide();
                                                	});
                                                  $("#me").click(function(){
                                                    	$("#text4").hide();
                                                    	});
                                                      $("#me").click(function(){
                                                        	$("#text1").hide();
                                                        	});
                                                          $("#me").click(function(){
                                                            	$("#text5").hide();
                                                            	});


})
